{% raw -%}
---
- name: Provision db server
  hosts: dbservers
  become: yes
  become_user: root
  remote_user: root

  vars_files:
    - ansible_vars/base.yml
    - ansible_vars/{{ env }}.yml

  roles:
    - ANXS.postgresql
    - base
{%- endraw %}
