---
- name: Deploy application
  hosts: webservers
  remote_user: {{ cookiecutter.application_user }}

{% raw -%}
  vars_files:
    - ansible_vars/base.yml
    - ansible_vars/{{ env }}.yml

  roles:
    - carlosbuenosvinos.ansistrano-deploy
{%- endraw %}
