{% raw -%}
---
- name: Provision web server
  hosts: webservers
  become: yes
  become_user: root
  remote_user: root

  vars_files:
    - ansible_vars/base.yml
    - ansible_vars/{{ env }}.yml

  roles:
    - nginx
    - base
    - application
{%- endraw %}
{%- if cookiecutter.add_celery_support == "y" %}
    - celery
{%- endif %}
{%- if cookiecutter.add_letsencrypt_certificate == "y" %}
    - thefinn93.letsencrypt 
{%- endif %}
