{% raw %}
---
- name: Install Nginx
  apt: name=nginx state=installed
  tags: packages

- name: Ensure that the default site is disabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
{% endraw %}