---
application_name: '{{ cookiecutter.application_slug }}'
application_root: '{{ cookiecutter.application_root }}'
application_user: '{{ cookiecutter.application_user }}'

postgresql_version: 9.3
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_cluster_name: 'main'
postgresql_app_user_password: 'POSTGRES_PASSWORD!!!'

{% raw %}
postgresql_databases:
  - name: '{{ application_name }}' 

postgresql_users:
  - name: '{{ application_name }}'
    pass: '{{ postgresql_app_user_password }}'

postgresql_user_privileges:
  - name: '{{ application_name }}'
    db: '{{ application_name }}'
{% endraw %}