---
application_name: '{{ cookiecutter.application_slug }}'
application_root: '{{ cookiecutter.application_root }}'
application_user: '{{ cookiecutter.application_user }}'

postgresql_version: 9.3
postgresql_encoding: 'UTF-8'
postgresql_locale: 'en_US.UTF-8'
postgresql_cluster_name: 'main'
postgresql_app_user_password: 'POSTGRES_PASSWORD!!!'

{% raw %}
postgresql_databases:
  - name: '{{ application_name }}' 

postgresql_users:
  - name: '{{ application_name }}'
    pass: '{{ postgresql_app_user_password }}'

postgresql_user_privileges:
  - name: '{{ application_name }}'
    db: '{{ application_name }}'
{% endraw %}

letsencrypt_email: '{{ cookiecutter.letsencrypt_email }}'
letsencrypt_pause_services: 'nginx'
letsencrypt_request_www: 'false'

# Ansistrano deploy settings
ansistrano_git_repo: '{{ cookiecutter.project_git_remote }}' # Location of the git repository
{% raw %}
ansistrano_deploy_via: "git"
ansistrano_keep_releases: 5
ansistrano_deploy_to: '{{ application_root }}'
ansistrano_git_identity_key_path: '~/.ssh/id_rsa'
ansistrano_shared_paths: ['media', 'staticfiles']
ansistrano_shared_files: []
ansistrano_after_cleanup_tasks_file: "{{ playbook_dir }}/deploy_tasks/after-cleanup.yml"
{% endraw %}
